apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeport.name }}
  namespace: {{ .Values.nodeport.namespace }}
spec:
  type: {{ .Values.nodeport.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 32593
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: {{ .Values.nodeport.app }}
