apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traefiknp.name }}
  namespace: {{ .Values.traefiknp.namespace }}
spec:
  type: {{ .Values.traefiknp.type }}
  ports:
  - port: {{ .Values.traefiknp.porthttp }}
    targetPort: {{ .Values.traefiknp.tghttp }}
    protocol: {{ .Values.traefiknp.protocol }}
    name: {{ .Values.traefiknp.http }}
    nodePort: {{ .Values.traefiknp.nodeport }}
  - port: {{ .Values.traefiknp.porthttps }}
    targetPort: {{ .Values.traefiknp.tghttps }}
    protocol: {{ .Values.traefiknp.protocol }}
    name: {{ .Values.traefiknp.https }}
  selector:
    app.kubernetes.io/name: {{ .Values.traefiknp.app }}
