apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.traefikname }}
  labels:
    app: {{ .Values.pgadmin.traefikname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pgadmin.traefikname }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgadmin.traefikname }}
    spec:
      containers:
        - name: {{ .Values.pgadmin.traefikname }}
          image: {{ .Values.pgadmin.image }}
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.pgadmin.password }}
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.email }}
            - name: SCRIPT_NAME 
              value: {{ .Values.pgadmin.traefikscriptname }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.traefikname }}-svc
  labels:
    app: {{ .Values.pgadmin.traefikname }}
spec:
  type: {{ .Values.pgadmin.serviceType }}
  ports:
    - port: {{ .Values.pgadmin.servicePort }}
  selector:
    app: {{ .Values.pgadmin.traefikname }}
