apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kongnp.name }}
  namespace: {{ .Values.kongnp.namespace }}
spec:
  type: {{ .Values.kongnp.type }}
  ports:
  - port: {{ .Values.kongnp.porthttp }}
    targetPort: {{ .Values.kongnp.tghttp }}
    protocol: {{ .Values.kongnp.protocol }}
    name: {{ .Values.kongnp.http }}
    nodePort: {{ .Values.kongnp.nodeport }}
  - port: {{ .Values.kongnp.porthttps }}
    targetPort: {{ .Values.kongnp.tghttps }}
    protocol: {{ .Values.kongnp.protocol }}
    name: {{ .Values.kongnp.https }}
  selector:
    app.kubernetes.io/name: {{ .Values.kongnp.app }}