# echoserver:
#   name: echoserver
#   image: ealen/echo-server:latest
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /kongecho
#   traefik_path: /traefikecho
#   pathType: Exact
# helloworld:
#   name: helloworld
#   image: tutum/hello-world:latest
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /konghello
#   traefik_path: /traefikhello
#   pathType: Exact
# pgadmin:
#   kong: kongpgadmin
#   traefik: traefikpgadmin
#   image: dpage/pgadmin4
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /kongpgadmin
#   traefik_path: /traefikpgadmin
#   pathType: Prefix
#   email: patiphan.t@appman.co.th
#   password: admin
#   kongscriptname: /kongpgadmin
#   traefikscriptname: /traefikpgadmin
# ingress:
#   kong_ingress: kong-ingress
#   kong_pgadmin_ingress: kong-pgadmin-ingress
#   traefik: traefik-ingress
#   host: nlb-new049-c8d0f10547200646.elb.ap-southeast-1.amazonaws.com
# kongig:
#   name: kong-ingress-controller
#   nodename: new-kong
#   namespaceapp: argocd
#   namespacedest: kong
#   project: default
#   chart: kong
#   repo: https://charts.konghq.com
#   targetrevision: 2.7.0
#   server: https://kubernetes.default.svc
# traefikig:
#   name: traefik-ingress-controller
#   nodename: new-traefik
#   namespaceapp: argocd
#   namespacedest: traefik
#   project: default
#   chart: traefik
#   repo: https://helm.traefik.io/traefik
#   targetrevision: 10.15.0
#   server: https://kubernetes.default.svc
# kongnp:
#   name: kong
#   namespace: kong
#   type: NodePort
#   porthttp: 80
#   porthttps: 443
#   tghttp: 8000
#   tghttps: 8443
#   protocal: TCP
#   nodeport: 32592
#   http: http
#   https: https
#   app: kong
# traefiknp:
#   name: traefik
#   namespace: traefik
#   type: NodePort
#   porthttp: 80
#   porthttps: 443
#   tghttp: 8000
#   tghttps: 8443
#   protocal: TCP
#   nodeport: 32591
#   http: http
#   https: https
#   app: traefik
